[TASK] Deprecate two TypoScript related exceptions
MissingTsfeException: This one is useless, we can
simply return false in the expression function
instead of throwing the exception.

InvalidTypoScriptConditionException: This was rendered
unused with the refactoring of the condition matcher
and expression language TypoScript implementation in
patch #100047.

Resolves: #100237
Related: #100047
Releases: main
Change-Id: Ic6732bbb07b5e38deee8d94921eac12041f00e38
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78195
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>